package br.com.cleanprosolutions.auth.document;

import br.com.cleanprosolutions.auth.enumerations.UserRole;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.Instant;

/**
 * MongoDB document representing user credentials in the auth-service.
 *
 * <p>Stores only authentication data (email, hashed password, role, tokens).
 * User profile data is managed by the {@code user-service}.</p>
 *
 * @author Clean Pro Solutions Team
 * @since 1.0.0
 */
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@Document(collection = "user_credentials")
public class UserCredential {

    /** Unique identifier generated by MongoDB. */
    @Id
    private String id;

    /** User email — unique index enforced at DB level. */
    @Indexed(unique = true)
    private String email;

    /** BCrypt-hashed password. Never stored in plain text. */
    private String passwordHash;

    /** User role in the platform. */
    private UserRole role;

    /** Current valid refresh token. Replaced on every login/refresh cycle. */
    private String refreshToken;

    /** Whether the account is active. Inactive accounts cannot authenticate. */
    private boolean active;

    /** Account creation timestamp (UTC). */
    private Instant createdAt;

    /** Last update timestamp (UTC). */
    private Instant updatedAt;
}
